/**
 * `product-feed-ingest` — how a brand puts its clothes into Selv.
 *
 * A brand POSTs a batch of products authenticated by a brand API key. Each
 * item is upserted into `brand_products` on `(brand_id, external_id)`, so the
 * brand can run this on a cron (hourly/nightly) with their full catalog and it
 * converges: new SKUs appear, changed prices update, nothing duplicates.
 *
 * DESIGN STANCE: partial success is the default.
 * A real product feed is generated by a script on the brand's side and will
 * contain bad rows — a null price on a pre-order item, an `http://` image URL
 * from a legacy CDN, a category we do not have. Failing the whole batch on one
 * of those means a brand's entire catalog silently stops updating because of a
 * single discontinued SKU. So every item is validated independently and the
 * response reports per-item errors, letting the brand fix rows incrementally
 * while the good 99% goes live immediately.
 *
 * CONTRACT
 * --------
 *   POST /functions/v1/product-feed-ingest
 *   Headers:
 *     Authorization: Bearer <brand_api_key>
 *     Content-Type: application/json
 *   Body:
 *     {
 *       "deactivate_missing": false,     // optional, see below
 *       "products": [{
 *         "external_id": "SKU-123",      // required, your own stable id
 *         "name": "Linen Camp Shirt",    // required
 *         "category": "top",             // required, see CATEGORIES
 *         "price_cents": 12900,          // required, integer cents
 *         "image_url": "https://...",    // required, https only
 *         "product_url": "https://...",  // required, https only
 *         "description": "...",          // optional
 *         "color": "sand",               // optional
 *         "sale_price_cents": 9900,      // optional
 *         "currency": "USD",             // optional, default USD
 *         "extra_image_urls": ["https://..."],  // optional
 *         "tryon_image_url": "https://...",     // optional
 *         "sizes": ["S","M","L"],        // optional
 *         "tags": ["linen","summer"],    // optional
 *         "in_stock": true,              // optional, default true
 *         "is_active": true              // optional, default true
 *       }]
 *     }
 *   200: { ok, upserted, skipped, deactivated, errors: [{ index, external_id, message }] }
 */

import {
  corsHeaders,
  handlePreflight,
  jsonResponse,
  newRequestId,
} from "../_shared/cors.ts";
import {
  extractBearerToken,
  supabaseAdmin,
} from "../_shared/supabaseAdmin.ts";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Mirrors the `garment_category` enum in supabase/schema.sql. */
const CATEGORIES = [
  "top",
  "bottom",
  "dress",
  "outerwear",
  "shoes",
  "accessory",
] as const;
type GarmentCategory = (typeof CATEGORIES)[number];

/**
 * Maximum products per request. A brand with a bigger catalog paginates.
 * The cap exists because an Edge Function has a hard wall-clock and memory
 * budget: a 10,000-row batch would time out mid-upsert and leave the brand
 * unable to tell which half landed.
 */
const MAX_BATCH_SIZE = 500;

/** Rows per database round-trip. Keeps individual statements bounded. */
const UPSERT_CHUNK_SIZE = 100;

/** Cap the request body so a runaway feed generator can't exhaust memory. */
const MAX_BODY_BYTES = 8 * 1024 * 1024;

const MAX_STRING_LEN = 512;
const MAX_DESCRIPTION_LEN = 8_000;
const MAX_URL_LEN = 2_048;
const MAX_ARRAY_LEN = 50;
const MAX_PRICE_CENTS = 100_000_000; // $1,000,000 — anything above is a units bug

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

/** SHA-256 of a string, lowercase hex. */
async function sha256Hex(input: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(input),
  );
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

interface AuthedBrand {
  brandId: string;
  apiKeyId: string;
}

/**
 * Authenticate the caller by brand API key.
 *
 * The raw key is never stored and never logged — only its SHA-256 hex digest
 * lives in `brand_api_keys.key_hash`, so a database dump does not hand an
 * attacker working credentials for every brand. (Plain SHA-256 rather than a
 * slow KDF is the right call here specifically because the key is a
 * high-entropy random string we generate, not a human-chosen password: there
 * is no dictionary to attack, so the only benefit of bcrypt/argon2 would be
 * latency on every single feed request.)
 *
 * `revoked_at is null` is part of the lookup rather than a post-check so a
 * revoked key simply does not match — there is no code path where a revoked
 * key resolves to a brand.
 */
async function authenticateBrand(
  req: Request,
  requestId: string,
): Promise<AuthedBrand | null> {
  const rawKey = extractBearerToken(req);
  if (!rawKey) return null;

  const keyHash = await sha256Hex(rawKey);

  const { data, error } = await supabaseAdmin
    .from("brand_api_keys")
    .select("id, brand_id")
    .eq("key_hash", keyHash)
    .is("revoked_at", null)
    .maybeSingle();

  if (error) {
    console.error(
      `[feed ${requestId}] brand_api_keys lookup failed:`,
      error.message,
    );
    return null;
  }
  if (!data) return null;

  // Best-effort usage tracking: powers "this brand's feed last ran 9 days ago"
  // alerting and lets Ben spot abandoned keys to revoke. Deliberately not
  // awaited-and-checked — a failure to stamp the timestamp must never block a
  // brand's catalog from updating.
  supabaseAdmin
    .from("brand_api_keys")
    .update({ last_used_at: new Date().toISOString() })
    .eq("id", data.id)
    .then(({ error: stampError }) => {
      if (stampError) {
        console.warn(
          `[feed ${requestId}] last_used_at stamp failed:`,
          stampError.message,
        );
      }
    });

  return { brandId: data.brand_id as string, apiKeyId: data.id as string };
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/**
 * Validate a URL that will be rendered in the Selv app or opened in the user's
 * browser.
 *
 * WHY THIS IS STRICTER THAN IT LOOKS LIKE IT NEEDS TO BE:
 * These strings are supplied by a third party and end up in two dangerous
 * places — an `<Image source={{ uri }}>` in the app, and a `Linking.openURL()`
 * when the user taps Buy. That makes the URL scheme a genuine attack surface:
 *
 *   - `javascript:` — `Linking.openURL` / a WebView will happily execute it.
 *     A compromised or malicious brand feed becomes script execution in the
 *     context of whatever opens it.
 *   - `data:` — an inline payload with no origin; used to smuggle HTML/SVG
 *     (SVG can carry script) past anything that only checks "is it a URL".
 *   - `file:` — can point at the device's local filesystem.
 *   - `http://` — plaintext. An image or a checkout link over http is
 *     interceptable and rewritable on any hostile network, which on the
 *     `product_url` path means an attacker can redirect a user mid-purchase.
 *     It also trips ATS on iOS and would fail to load anyway.
 *
 * Allowlisting `https:` (rather than blocklisting the bad schemes) is the only
 * approach that stays correct as new schemes appear.
 */
function validateHttpsUrl(value: unknown, field: string): string | null {
  if (typeof value !== "string" || value.trim().length === 0) {
    return `\`${field}\` is required and must be a string.`;
  }
  if (value.length > MAX_URL_LEN) {
    return `\`${field}\` exceeds ${MAX_URL_LEN} characters.`;
  }

  let parsed: URL;
  try {
    parsed = new URL(value.trim());
  } catch {
    return `\`${field}\` is not an absolute URL (it must start with https://).`;
  }

  if (parsed.protocol !== "https:") {
    return (
      `\`${field}\` must use https://. Got "${parsed.protocol}//" — http, ` +
      "data:, javascript: and file: URLs are rejected because these values " +
      "are rendered in the app and opened in the shopper's browser."
    );
  }

  if (!parsed.hostname || parsed.hostname.length === 0) {
    return `\`${field}\` has no hostname.`;
  }

  return null;
}

function optionalString(
  value: unknown,
  field: string,
  maxLen: number,
): { ok: true; value: string | null } | { ok: false; error: string } {
  if (value === undefined || value === null) return { ok: true, value: null };
  if (typeof value !== "string") {
    return { ok: false, error: `\`${field}\`, when present, must be a string.` };
  }
  if (value.length > maxLen) {
    return { ok: false, error: `\`${field}\` exceeds ${maxLen} characters.` };
  }
  const trimmed = value.trim();
  return { ok: true, value: trimmed.length > 0 ? trimmed : null };
}

function optionalStringArray(
  value: unknown,
  field: string,
): { ok: true; value: string[] } | { ok: false; error: string } {
  if (value === undefined || value === null) return { ok: true, value: [] };
  if (!Array.isArray(value)) {
    return { ok: false, error: `\`${field}\`, when present, must be an array of strings.` };
  }
  if (value.length > MAX_ARRAY_LEN) {
    return { ok: false, error: `\`${field}\` may contain at most ${MAX_ARRAY_LEN} entries.` };
  }
  const out: string[] = [];
  for (const entry of value) {
    if (typeof entry !== "string") {
      return { ok: false, error: `\`${field}\` must contain only strings.` };
    }
    const trimmed = entry.trim();
    if (trimmed.length === 0) continue;
    if (trimmed.length > MAX_STRING_LEN) {
      return { ok: false, error: `An entry in \`${field}\` exceeds ${MAX_STRING_LEN} characters.` };
    }
    out.push(trimmed);
  }
  return { ok: true, value: out };
}

function optionalBoolean(
  value: unknown,
  field: string,
  fallback: boolean,
): { ok: true; value: boolean } | { ok: false; error: string } {
  if (value === undefined || value === null) return { ok: true, value: fallback };
  if (typeof value !== "boolean") {
    return { ok: false, error: `\`${field}\`, when present, must be a boolean.` };
  }
  return { ok: true, value };
}

function priceCents(
  value: unknown,
  field: string,
  required: boolean,
): { ok: true; value: number | null } | { ok: false; error: string } {
  if (value === undefined || value === null) {
    if (required) return { ok: false, error: `\`${field}\` is required.` };
    return { ok: true, value: null };
  }
  if (typeof value !== "number" || !Number.isInteger(value)) {
    return {
      ok: false,
      error:
        `\`${field}\` must be an integer number of cents (e.g. 12900 for ` +
        "$129.00), not a decimal or a string.",
    };
  }
  if (value < 0) return { ok: false, error: `\`${field}\` must be >= 0.` };
  if (value > MAX_PRICE_CENTS) {
    return {
      ok: false,
      error:
        `\`${field}\` exceeds ${MAX_PRICE_CENTS} cents (this usually means the ` +
        "price was sent in a unit other than cents).",
    };
  }
  return { ok: true, value };
}

interface ProductRow {
  brand_id: string;
  external_id: string;
  name: string;
  description: string | null;
  category: GarmentCategory;
  color: string | null;
  price_cents: number;
  sale_price_cents: number | null;
  currency: string;
  image_url: string;
  extra_image_urls: string[];
  tryon_image_url: string | null;
  product_url: string;
  sizes: string[];
  tags: string[];
  in_stock: boolean;
  is_active: boolean;
  updated_at: string;
}

interface ItemError {
  index: number;
  external_id: string | null;
  message: string;
}

/**
 * Validate one feed item into a database row.
 *
 * `brandId` is passed in from the authenticated API key and stamped onto the
 * row here. NOTE that the caller's own `brand_id` field (if they send one) is
 * ignored entirely — see the comment on the upsert for why this is the single
 * most important line in the file.
 */
function validateProduct(
  raw: unknown,
  index: number,
  brandId: string,
  now: string,
): { ok: true; row: ProductRow } | { ok: false; error: ItemError } {
  const fail = (message: string, externalId: string | null = null) => ({
    ok: false as const,
    error: { index, external_id: externalId, message },
  });

  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    return fail("Product must be a JSON object.");
  }
  const p = raw as Record<string, unknown>;

  // --- external_id ---------------------------------------------------------
  if (
    typeof p.external_id !== "string" ||
    p.external_id.trim().length === 0 ||
    p.external_id.length > MAX_STRING_LEN
  ) {
    return fail(
      "`external_id` is required and must be a non-empty string of at most " +
        `${MAX_STRING_LEN} characters. It must be stable across feed runs — ` +
        "it is the key we upsert on.",
    );
  }
  const externalId = p.external_id.trim();

  // --- name ----------------------------------------------------------------
  if (
    typeof p.name !== "string" ||
    p.name.trim().length === 0 ||
    p.name.length > MAX_STRING_LEN
  ) {
    return fail(
      `\`name\` is required and must be a non-empty string of at most ${MAX_STRING_LEN} characters.`,
      externalId,
    );
  }

  // --- category ------------------------------------------------------------
  if (
    typeof p.category !== "string" ||
    !CATEGORIES.includes(p.category as GarmentCategory)
  ) {
    return fail(
      "`category` is required and must be one of: " + CATEGORIES.join(", ") + ".",
      externalId,
    );
  }

  // --- prices --------------------------------------------------------------
  const price = priceCents(p.price_cents, "price_cents", true);
  if (!price.ok) return fail(price.error, externalId);

  const salePrice = priceCents(p.sale_price_cents, "sale_price_cents", false);
  if (!salePrice.ok) return fail(salePrice.error, externalId);

  // --- currency ------------------------------------------------------------
  let currency = "USD";
  if (p.currency !== undefined && p.currency !== null) {
    if (typeof p.currency !== "string" || !/^[A-Za-z]{3}$/.test(p.currency)) {
      return fail('`currency` must be a 3-letter ISO 4217 code, e.g. "USD".', externalId);
    }
    currency = p.currency.toUpperCase();
  }

  // --- URLs ----------------------------------------------------------------
  const imageError = validateHttpsUrl(p.image_url, "image_url");
  if (imageError) return fail(imageError, externalId);

  const productUrlError = validateHttpsUrl(p.product_url, "product_url");
  if (productUrlError) return fail(productUrlError, externalId);

  let tryonImageUrl: string | null = null;
  if (p.tryon_image_url !== undefined && p.tryon_image_url !== null) {
    const err = validateHttpsUrl(p.tryon_image_url, "tryon_image_url");
    if (err) return fail(err, externalId);
    tryonImageUrl = (p.tryon_image_url as string).trim();
  }

  const extraImages = optionalStringArray(p.extra_image_urls, "extra_image_urls");
  if (!extraImages.ok) return fail(extraImages.error, externalId);
  for (const url of extraImages.value) {
    const err = validateHttpsUrl(url, "extra_image_urls[]");
    if (err) return fail(err, externalId);
  }

  // --- optional scalars ----------------------------------------------------
  const description = optionalString(p.description, "description", MAX_DESCRIPTION_LEN);
  if (!description.ok) return fail(description.error, externalId);

  const color = optionalString(p.color, "color", MAX_STRING_LEN);
  if (!color.ok) return fail(color.error, externalId);

  const sizes = optionalStringArray(p.sizes, "sizes");
  if (!sizes.ok) return fail(sizes.error, externalId);

  const tags = optionalStringArray(p.tags, "tags");
  if (!tags.ok) return fail(tags.error, externalId);

  const inStock = optionalBoolean(p.in_stock, "in_stock", true);
  if (!inStock.ok) return fail(inStock.error, externalId);

  const isActive = optionalBoolean(p.is_active, "is_active", true);
  if (!isActive.ok) return fail(isActive.error, externalId);

  return {
    ok: true,
    row: {
      // Stamped from the authenticated key, never from the payload.
      brand_id: brandId,
      external_id: externalId,
      name: p.name.trim(),
      description: description.value,
      category: p.category as GarmentCategory,
      color: color.value,
      price_cents: price.value as number,
      sale_price_cents: salePrice.value,
      currency,
      image_url: (p.image_url as string).trim(),
      extra_image_urls: extraImages.value,
      tryon_image_url: tryonImageUrl,
      product_url: (p.product_url as string).trim(),
      sizes: sizes.value,
      tags: tags.value,
      in_stock: inStock.value,
      is_active: isActive.value,
      updated_at: now,
    },
  };
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

Deno.serve(async (req: Request): Promise<Response> => {
  const preflight = handlePreflight(req);
  if (preflight) return preflight;

  const requestId = newRequestId();

  if (req.method !== "POST") {
    return jsonResponse(req, 405, {
      ok: false,
      error: "Method not allowed. Use POST.",
      request_id: requestId,
    });
  }

  try {
    // --- 1. Authenticate ----------------------------------------------------
    const brand = await authenticateBrand(req, requestId);
    if (!brand) {
      // Deliberately identical response for "no header", "malformed header",
      // "unknown key" and "revoked key" — distinguishing them would let a
      // caller probe which keys exist.
      return jsonResponse(req, 401, {
        ok: false,
        error:
          "Invalid or missing brand API key. Send it as " +
          "`Authorization: Bearer <key>`.",
        request_id: requestId,
      });
    }

    // --- 2. Parse the body --------------------------------------------------
    const rawBody = await req.text();
    if (rawBody.length > MAX_BODY_BYTES) {
      return jsonResponse(req, 413, {
        ok: false,
        error: `Request body exceeds ${MAX_BODY_BYTES} bytes. Send fewer products per request.`,
        request_id: requestId,
      });
    }

    let parsed: unknown;
    try {
      parsed = JSON.parse(rawBody);
    } catch {
      return jsonResponse(req, 400, {
        ok: false,
        error: "Request body is not valid JSON.",
        request_id: requestId,
      });
    }

    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      return jsonResponse(req, 400, {
        ok: false,
        error: 'Request body must be a JSON object with a `products` array.',
        request_id: requestId,
      });
    }

    const payload = parsed as Record<string, unknown>;
    const products = payload.products;

    if (!Array.isArray(products)) {
      return jsonResponse(req, 400, {
        ok: false,
        error: "`products` is required and must be an array.",
        request_id: requestId,
      });
    }
    if (products.length === 0) {
      return jsonResponse(req, 400, {
        ok: false,
        error: "`products` must contain at least one item.",
        request_id: requestId,
      });
    }
    if (products.length > MAX_BATCH_SIZE) {
      return jsonResponse(req, 400, {
        ok: false,
        error:
          `\`products\` contains ${products.length} items; the maximum is ` +
          `${MAX_BATCH_SIZE} per request. Paginate your feed.`,
        request_id: requestId,
      });
    }

    const deactivateMissing = payload.deactivate_missing === true;

    // --- 3. Validate every item independently -------------------------------
    const now = new Date().toISOString();
    const rows: ProductRow[] = [];
    const errors: ItemError[] = [];

    // Within a single batch, two rows with the same external_id would make
    // Postgres throw "ON CONFLICT DO UPDATE command cannot affect row a second
    // time" and take down the ENTIRE chunk — the exact whole-batch failure this
    // endpoint is designed to avoid. So in-batch duplicates are caught here and
    // only the first occurrence is kept; later ones are reported as item errors
    // (a duplicate SKU in a feed is a bug on the brand's side worth surfacing).
    const seen = new Map<string, number>();

    for (let i = 0; i < products.length; i++) {
      const result = validateProduct(products[i], i, brand.brandId, now);
      if (!result.ok) {
        errors.push(result.error);
        continue;
      }

      const firstIndex = seen.get(result.row.external_id);
      if (firstIndex !== undefined) {
        errors.push({
          index: i,
          external_id: result.row.external_id,
          message:
            `Duplicate \`external_id\` within this batch (first seen at index ` +
            `${firstIndex}). Only the first occurrence was applied.`,
        });
        continue;
      }

      seen.set(result.row.external_id, i);
      rows.push(result.row);
    }

    // --- 4. Upsert ----------------------------------------------------------
    //
    // SECURITY-CRITICAL: `brand_id` on every row comes from `brand.brandId`,
    // which was derived from the hashed API key in step 1. Any `brand_id` the
    // caller put in the payload was discarded during validation and is never
    // read. This is the whole tenancy boundary of the endpoint: without it, any
    // brand holding a valid key could overwrite a competitor's catalog —
    // change their prices, swap their images, or point their `product_url` at
    // their own store. Because we use the service-role client (which bypasses
    // RLS), there is no second line of defence here. Do not "helpfully" accept
    // a brand_id from the body, not even behind a flag.
    let upserted = 0;

    for (let offset = 0; offset < rows.length; offset += UPSERT_CHUNK_SIZE) {
      const chunk = rows.slice(offset, offset + UPSERT_CHUNK_SIZE);

      const { error: chunkError } = await supabaseAdmin
        .from("brand_products")
        .upsert(chunk, { onConflict: "brand_id,external_id" });

      if (!chunkError) {
        upserted += chunk.length;
        continue;
      }

      // A chunk-level failure is usually systemic (bad column, constraint
      // change), but it can also be one poisoned row — e.g. a value that
      // passes our checks but violates a database constraint we do not know
      // about. Retry the chunk row-by-row so a single bad row costs one
      // product rather than a hundred, and so the brand gets a precise index.
      console.warn(
        `[feed ${requestId}] chunk upsert failed (${chunk.length} rows), ` +
          `falling back to per-row:`,
        chunkError.message,
      );

      for (const row of chunk) {
        const { error: rowError } = await supabaseAdmin
          .from("brand_products")
          .upsert(row, { onConflict: "brand_id,external_id" });

        if (rowError) {
          console.error(
            `[feed ${requestId}] row upsert failed for external_id=${row.external_id}:`,
            rowError.message,
          );
          errors.push({
            index: seen.get(row.external_id) ?? -1,
            external_id: row.external_id,
            // Generic on purpose — the raw Postgres message can carry
            // constraint and column names we do not want to hand out.
            message: "Database rejected this product. Contact Selv support with the request id.",
          });
        } else {
          upserted += 1;
        }
      }
    }

    // --- 5. Optional full-feed-replace --------------------------------------
    //
    // `deactivate_missing` implements standard full-feed semantics: anything
    // the brand did NOT send in this batch is assumed discontinued and is
    // soft-deactivated (`is_active = false`, never deleted, so historical
    // clicks and conversions keep their foreign keys and a re-listed SKU
    // reactivates with its history intact).
    //
    // THE RISK, STATED PLAINLY: if a brand's feed generator half-fails and
    // sends 12 products instead of 1,200, this flag deactivates the other
    // 1,188 — their entire Selv storefront disappears until the next good run.
    // Two guards mitigate that:
    //   (a) it only runs when the batch had ZERO item errors, so a partially
    //       broken feed never triggers a mass deactivation; and
    //   (b) it is opt-in per request, so a brand that paginates (and therefore
    //       must never use it, since each page "misses" the others) has to
    //       actively ask for it.
    // A brand paginating a >500 SKU catalog should NOT use this flag; they
    // should deactivate explicitly by sending `is_active: false`.
    let deactivated: number | null = null;

    if (deactivateMissing) {
      if (errors.length > 0) {
        console.warn(
          `[feed ${requestId}] deactivate_missing requested but the batch had ` +
            `${errors.length} item error(s) — skipping deactivation to avoid ` +
            "taking a brand's catalog offline from a partial feed.",
        );
      } else {
        const submitted = new Set(rows.map((r) => r.external_id));

        const { data: existing, error: listError } = await supabaseAdmin
          .from("brand_products")
          .select("external_id")
          .eq("brand_id", brand.brandId)
          .eq("is_active", true);

        if (listError) {
          console.error(
            `[feed ${requestId}] deactivate_missing listing failed:`,
            listError.message,
          );
        } else {
          const missing = (existing ?? [])
            .map((r) => r.external_id as string)
            .filter((id) => !submitted.has(id));

          deactivated = 0;
          for (let offset = 0; offset < missing.length; offset += UPSERT_CHUNK_SIZE) {
            const chunk = missing.slice(offset, offset + UPSERT_CHUNK_SIZE);
            const { error: deactivateError } = await supabaseAdmin
              .from("brand_products")
              .update({ is_active: false, updated_at: now })
              .eq("brand_id", brand.brandId)
              .in("external_id", chunk);

            if (deactivateError) {
              console.error(
                `[feed ${requestId}] deactivation chunk failed:`,
                deactivateError.message,
              );
            } else {
              deactivated += chunk.length;
            }
          }
        }
      }
    }

    console.log(
      `[feed ${requestId}] brand=${brand.brandId} key=${brand.apiKeyId} ` +
        `received=${products.length} upserted=${upserted} ` +
        `skipped=${errors.length} deactivated=${deactivated ?? "n/a"}`,
    );

    return jsonResponse(req, 200, {
      ok: errors.length === 0,
      upserted,
      skipped: errors.length,
      deactivated,
      errors,
      request_id: requestId,
    });
  } catch (err) {
    console.error(
      `[feed ${requestId}] unhandled error:`,
      err instanceof Error ? err.stack ?? err.message : String(err),
    );
    return new Response(
      JSON.stringify({
        ok: false,
        error: "Internal error. Please retry.",
        request_id: requestId,
      }),
      { status: 500, headers: corsHeaders(req) },
    );
  }
});
